# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 954889be5c12fceced2b7d43d4e8cb5b8b86f12899dfe96adbef26b1c4f7cd680f62222960d0ceeaadffed6ab050182c922ec67204173beb64ccdf25ffe8f68d

test:
  secret_key_base: 7b2bddf09575f5453de4d53e701f5953b33d3f02732ea454772f7f1ca1d0735a50015f0c09494bb3ad230030dcac0a25f614a9cfd21e05b52385dde649e76dea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
